# Generated by Django 3.2.15 on 2022-09-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
