# Generated by Django 3.2.15 on 2022-09-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.PositiveBigIntegerField(default=50),
            preserve_default=False,
        ),
    ]
