# Generated by Django 3.2.15 on 2022-09-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=b'I01\n', max_length=20, null=b'I01\n'),
        ),
    ]
